### ISSUE TITLE
Undefined variable referenced (typo?)

### ISSUE THREAD

**Issue by atz** [sul-dlss/dor-workflow-service#12]
In this line:
https://github.com/sul-dlss/dor-workflow-service/blob/develop/lib/dor/services/workflow_service.rb#L486

is the only appearance of `@workflow_resource`.  This should be `workflow_resource` like the rest, right?

If so, there is something off with testing as well, since this kind of thing should otherwise be caught.

**Comment by drh-stanford** [comment]
Yes, this looks like a typo ... it shouldn't work since it's a class method.
