### ISSUE TITLE
Merge with dor-services gem?

### ISSUE THREAD

**Issue by atz** [sul-dlss/dor-workflow-service#15]
This code has basically one class and one test file.  It uses the same `Dor` namespace as dor-services.   Dor-services is a client gem.  Dor-workflow-service is a client gem. It uses a subset of dor-services dependencies.  Dor-services uses dor-workflow-service, so the compatibility constraints of the broader gem are already applicable here, but the functionality exposed is limited.  From my perspective, consumers of this gem are likely to be dor-services consumers also.  It seems like a maintenance benefit to merge this code into dor-services.  In particular, to establish and maintain common logging and HTTP (proxy, retry, timeout) behavior, having the code in one place seems advantageous.  

Opinions?  Blockers?

**Comment by drh-stanford** [comment]
I assume that it was kept as its own gem so non-dor-services clients could interact with the workflow service (without the config baggage of dor-services). I'm not aware of any such clients though. Maybe the workflow archiver, although I think it interacts with the database directly.

**Comment by cbeer** [comment]
`sdr-preservation-core` uses `dor-workflow-service` directly.
