### ISSUE TITLE
refactor how we build query string parameters

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/dor-workflow-service#33]
See #32 for initial discussion.

Basically, Faraday recommends the following pattern for passing query string parameters to the http request: 

```
opts[:params] = { completed: ['a', 'b'], waiting: 'c' }
```

**Comment by atz** [comment]
@drh-stanford: this is now resolved?

**Comment by drh-stanford** [comment]
Yes PR #32 fixed this issue.
